[project]
name = "pfdelta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argcomplete>=3.6.2",
    "gitpython==3.1.44",
    "huggingface-hub[cli]>=0.33.2",
    "ipdb==0.13.13",
    "ipykernel>=6.29.5",
    "kaleido>=1.0.0",
    "matplotlib>=3.10.3",
    "nbformat>=5.10.4",
    "numpy==1.26.3",
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "pypower==5.1.17",
    "pyrlu==0.2.1",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.7.0",
    "scipy==1.15.1",
    "seaborn>=0.13.2",
    "torch-geometric==2.6.1",
    "torch==2.1.2",
    "torchaudio==2.1.2",
    "torchvision==0.16.2",
]

