config_type: local_simple_batch
batch_name: my_local_test
model:
  name: mlp
  hidden_size: _manual_list(16, 32, 64, 128, 256 | mini, small, medium, large, massive)
dataset:
  datasets:
  - name: fashion # First is for training
    train: False
  - name: fashion # Rest are for validation
    train: False
  - name: fashion
    train: False
optim:
  optimizer:
    name: "Adam"
    lr: _manual_list(0.1, 0.01, 0.001, 0.0001 | 1e1, 1e2, 1e3, 1e4)
    weight_decay: 0
  train_params:
    epochs: 5
    batch_size: _manual_list(64, 128, 256 | mini, medium, large)
    train_loss:
    - CrossEntropyLoss          # First is for training
    - ClassificationAccuracy    # Rest are for tracking
  val_params:
    report_every: 3 # How often to calculate val error
    batch_size: 256
    high_is_good: True
    val_loss:
    - ClassificationAccuracy # First used for best model
    - CrossEntropyLoss # Rest are for tracking
functional:
  run_name: mytest_lr%lr_hs%hidden_size_bs%batch_size
  run_location: tutorial_runs/many_experiments
