config_type: experiment
model:
  name: mlp
  hidden_size: 128
dataset:
  datasets:
  - name: fashion # First is for training
    train: False
  - name: fashion # Rest are for validation
    train: False
  - name: fashion
    train: False
optim:
  optimizer:
    name: "Adam"
    lr: 0.001
    weight_decay: 0.
  train_params:
    epochs: 100
    batch_size: 256
    train_loss:
    - CrossEntropyLoss # First is for training
    - ClassificationAccuracy # Rest are for tracking
  val_params:
    report_every: 5 # How often to calculate val error
    batch_size: 256
    early_stop:
      decrease_for: 10 # Needs to be a divisor of report_every
      decrease_by: 0.01
      needs_best_every: 15
    high_is_good: True
    val_loss:
    - ClassificationAccuracy # First used for best model
    - CrossEntropyLoss # Rest are for tracking
functional:
  run_name: mytest
  run_location: tutorial_runs/one_experiment
